"""
Script pour trouver l'URL du backend en production
"""

print("="*80)
print("TROUVER L'URL DU BACKEND")
print("="*80)
print()
print("Le backend et le frontend sont deux services séparés sur Render.")
print("Le frontend est sur: whatsapp.lamaisonduchauffeurvtc.fr")
print("Le backend a une URL différente.")
print()
print("MÉTHODE 1: Via Render Dashboard (Recommandé)")
print("-" * 80)
print("1. Allez sur https://dashboard.render.com")
print("2. Cliquez sur le service 'whatsapp-inbox-backend'")
print("3. L'URL est affichée en haut, elle ressemble à:")
print("   https://whatsapp-inbox-backend-xxxx.onrender.com")
print()
print("MÉTHODE 2: Via les variables d'environnement du frontend")
print("-" * 80)
print("1. Dans Render Dashboard → 'whatsapp-inbox-frontend'")
print("2. Allez dans 'Environment'")
print("3. Cherchez 'VITE_BACKEND_URL'")
print("4. Cette valeur est l'URL du backend")
print()
print("MÉTHODE 3: Tester différentes URLs possibles")
print("-" * 80)
print("Essayez ces URLs dans votre navigateur:")
print("  - https://whatsapp-inbox-backend.onrender.com/healthz")
print("  - https://whatsapp-inbox-backend-xxxx.onrender.com/healthz")
print()
print("Si vous voyez {'status':'ok'} ou similaire, c'est la bonne URL!")
print()
print("="*80)
print("⚠️ IMPORTANT: /webhook/whatsapp/debug est un POST, pas un GET")
print("="*80)
print()
print("Quand vous accédez à /webhook/whatsapp/debug dans le navigateur,")
print("vous faites un GET, mais cet endpoint nécessite un POST.")
print()
print("Pour tester, utilisez curl ou un outil comme Postman:")
print()
print("curl -X POST https://BACKEND_URL/webhook/whatsapp/debug \\")
print("  -H 'Content-Type: application/json' \\")
print("  -d '{\"field\":\"messages\",\"value\":{...}}'")
print()
print("="*80)

